bootstrap: docker
from: ubuntu:16.04

 % help
An Ubuntu 16.04 Singularity container with basic Python 3.5 and packages

%post
    apt-get update
    apt-get -y install \
                    vim \
                    python3 \
                    python3-dev \
                    python3-setuptools \
                    python3-pip \

    # install python packages
    pip install numpy==1.15.1 \
        pandas==0.23.4 \
        scipy==1.1.0 \ 
        scikit-learn==0.19.2 \




