bootstrap: docker
from: ubuntu:17.10

 % help
An Ubuntu 17.10 Singularity container with basic Python 3.6.3 and packages

%post
    apt-get update
    apt-get -y install \
                    vim \
                    git \
                    zsh \
                    wget \
                    python3 \
                    python3-dev \
                    python3-setuptools \
                    python3-pip

    # Install oh-my-zsh
     wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true
    # set zsh as shell
    # export SINGULARITY_SHELL="/bin/bash --norc"
    # export SINGULARITY_SHELL=/bin/zsh
    # /bin/zsh --login

    ## Make sure the shell always shows that we are in
    #echo "PROMPT=\"(singularity) \$PROMPT\"" >> $HOME/.zshrc

    pip3 --no-cache-dir install \
         numpy==1.15.1 \
         pandas==0.23.4 \
         scipy==1.1.0 \
         scikit-learn==0.19.2

    # mount necessary folders to the container
    # export SINGULARITY_BINDPATH="/home/vagrant/BayOpt:/home/BayOpt/"



