#!/bin/bash --login
# How much memory needed *per core*
#$ -l h_vmem=1G

# Which operating system to use
#$ -l cns_os=el7

# Which queues the job should use:
# NOTE: mpi use multiple cores on different machines
#       smp use multiple cores on the same machine
#$ -pe smp 1

#$ -t 10-110:10
# Where to save the STDOUT and STDERR
#$ -o ~/BayOpt/singularity/logs/ukbio
#$ -e ~/BayOpt/singularity/logs/ukbio

/home/k1506210/BayOpt/singularity/exec_BayOpt_BANC.sh /sing/neuroenvpy.sh \
/code/BayOptPy/tpot/brain_age_analysis.py -raw False -model regression \
-predicted_attribute age -dataset freesurf_combined -cv 10 \
-generations 10 -population_size 1000 -offspring_size 100 -config_dict vanilla_combi \
-njobs 1 -random_seed $SGE_TASK_ID -analysis vanilla_combi -mutation_rate 0.5 \
-crossover_rate 0.5
